server:
  port: 9002

spring:
  application:
    name: orders-service

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttemps:  3
        waitDuration:  3s
  ratelimiter:
    instances:
      basicExample:
        limitForPeriod: 2
        limitRefreshPeriod: 3s
        timeoutDuration: 1s

