server:
  port: 9002

spring:
  application:
    name: orders-service

  config:
    import: "optional:configserver:"
resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttemps:  3
        waitDuration:  3s
  ratelimiter:
    instances:
      basicExample:
        limitForPeriod: 2
        limitRefreshPeriod: 3s
        timeoutDuration: 1s


